name: Unit Test
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 12, 14, 16, 18 ]
    steps:
      uses: actions/checkout@v3
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      run: |
        npm install
        npm install -g codecov
        npm run cover
        codecov